#language: java
#jdk:
#  - openjdk11
#services:
#  - docker
#
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker pull openjdk:11-jre-slim-sid
#script:
#  - ./mvnw clean install
#  - ./mvnw deploy jib:build -P deploy-docker

language: java
jdk:
  - openjdk17
env:
  global:
    - DOCKER_USERNAME=quang1709
    - DOCKER_PASSWORD=argargargtbn1
before_install:
  - sudo chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:17-jdk-slim
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker