language: java
jdk:
  - openjdk17
env:
  global:
    - DOCKER_USERNAME=quang1709
    - DOCKER_PASSWORD=argargargtbn1
before_install:
  - sudo chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull mediasol/openjdk17-slim-jprofiler
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker