language: java
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    - DOCKER_USERNAME=quang1709
    - DOCKER_PASSWORD=argargargtbn1
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)


